David/multi list and list
hibobio/bob-style pull request #1827
Opened 2020-11-12 11:32 UTC by SkyWallkeRed

IN DEVELOPMENT

TODO: tests 

requesting a check before i write the tests.

2020-11-15 08:01 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +        }
i think this should be default hardcoded behaviour, without strongParent toggle.

2020-11-15 08:04 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +          option.label = [...option.label, ''];
needs to be empty space if you really mean to put an empty column, otherwise its falsy and wont achieve anything

'' => ' '

2020-11-15 08:06 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +        }
you dont really need the if's. you can just assign, and its undefined - its same thing as not assigning.

so it will be a bit more compact if you just use map instead of the forEach, and just map to an object: 

```
{
  id: op.id,
  label: [`<strong>${optionGroup.groupName}</strong> - ${op.value}`, op.subValue || ' '],
  icon: this.listViewConfig.rowStartIcon,
  actionIcon = this.listViewConfig?.rowAction?.icon,
 ... etc ...
}
```

2020-11-15 08:15 UTC, SkyWallkeRed commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +        }
the design have 3 states one is with strong one is without

2020-11-15 08:40 UTC, galloween requested changes
see comments

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +
i think you dont need actionType - you either have menu or not - its enough to decide what template to use

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +
also not sure what rowTableView is for - you are supposed to have same amount of labels for every item.
if you think there may be cases, where some items have subValue and some not - just add the empty cell for those items that dont have it (below)

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +  icon?: Icons;
icon already exists in BasicListItem, so no need to repeat

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +  styleUrls: ['./multi-list-and-list.component.scss'],
if you are re-using classes and styles from the MLAC component, just add an import to its scss file here, before the multi-list-and-list

for classes, unique to this component, lets use MLAL prefix (the C in the MLAC was chips)

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +  @Input() iconColor: IconColor;
where do these go?
iconColor i saw in template, but icon is not used i think.

also, lets have iconColor hardcoded for now. there is no need to have to pass it all the time

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +        }
the `|| ' '` trick is only needed if there might be some items with subValue and some without. 
If all of them are expected to be the same, you can do this:
```
[`<strong>${optionGroup.groupName}</strong> - ${op.value}`, ...(op.subValue ? [op.subValue] : [])]
```
or
```
[`<strong>${optionGroup.groupName}</strong> - ${op.value}`, op.subValue].filter(Boolean)
```

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.module.ts
> +    // ButtonsModule,
remove

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.module.ts
> +// import { BasicListModule, ButtonsModule } from 'bob-style';
remove

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.module.ts
> +import { EmptyStateModule } from 'bob-style';
imports from within same library should always be relative

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.scss
> +      display: table;
you cant do this. it breaks the table

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.scss
> +      text-align: right;
this is unpredictable.
if you mean to address second label cell, use:
```.bbl-list-label + .bbl-list-label```

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.scss
> +      width: 10px;
again, this is unpredictable.
if you mean to address the cell with the action, use `.bbl-list-action-container`
but why would you need to set its width to 10px????

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.scss
> +  overflow-y: scroll;
bad idea. 
1) remove overflow from table, you already have it on the container - b-basic-list
2) remove min-height from table; to manage the border, remove box-shadow from `.bbl-lis body` and add border and border-radius to `b-basic-list`

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +  @Input() public type: BasicListType = BasicListType.primary;
this should be either hardcoded or omitted. no need to config it at the moment

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.scss
> +  overflow-y: scroll;
remove overflow. it can manage its own overflow

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.scss
> +  overflow-y: scroll;
(and better just keep the styles from MLAC, no need to invent again)

2020-11-15 08:40 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.scss
> +  overflow-y: scroll;
use `auto` instead of `scroll` so that scrollbar does not show when not needed

2020-11-15 08:42 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +        }
can you add link to design in PR description so that i can take a look?

2020-11-15 08:44 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.scss
> +      width: 10px;
also it will have no affect on the table, it will still grow to whatever size it wants

2020-11-15 08:48 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +
when all the group is selected, are you sure you want to add all options separately?
(just checking)

2020-11-15 10:28 UTC, SkyWallkeRed commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +        }
https://www.figma.com/file/e5kH0ehswD91XqrcvwdIy0/Flows?node-id=0%3A1

2020-11-15 11:01 UTC, SkyWallkeRed commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +
it will be inited with mode: SelectMode = SelectMode.checkGroups; so there is no option to select more then one in group, i dod that to support a generic structure..

2020-11-15 11:05 UTC, SkyWallkeRed commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +        }
i did that to support more generic use cases, its not needed in the design, (good to have ?)

2020-11-17 14:59 UTC, galloween reviewed
ok there is something we can (possibly) do better (maybe) 
if you chose to go your own way with this - its also ok

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.html
> +                [mode]="mode"
when i meant "re-use/keep styles and classes from MLAchips" i meant :
- keep the mlac classes as much as possible, 
- dont duplicate **none** of the scss, instead just use the same file in component metadata:
`styleUrls: ['..path-to/mlac/mlac.style.file.scss',  './multi-list-and-list.component.scss'],`
- for unique stuff (that doesnt have a similar thing in MLAchips), use the new mlal prefix

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.scss
> +
alternatively, you could also import the MLAC file here

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +      if (op.selected) {
indeed in this case map doesnt make any sense, as you are not mapping but pushing to external array (my advise doesnt fit here).
so stay with forEach :)

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +    this.options = listChange.getSelectGroupOptions();
with the better approach than mlac, with separating options from value,
you dont need to save the options, they are (basically) the same as you got as input,

what you need is:

this.value = listChange.delectedIDs;
this.optionsToList( listChange.getSelect<u>**ed**</u>GroupOptions(), this.value  );

selectED group options is - you guessed it - just the selected options,
second argument (value) is explained below

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +  @Input() options: SelectGroupOption[] = [];
i think we can do something better than the MLAC.

lets add `@Input() value: (string|number)[];`  <- list of selected IDs, same as multi-list component's value

this way we can separate options from value, it will be much nicer

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +  private optionsToList(options: SelectGroupOption[]): ListRow[] {
in the new approach, you need both options AND value:

 private optionsToList( options: SelectGroupOption[], value: (string|number)[] ) {}

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +      if (op.selected) {
and the selected check becomes:

if ( isArray(this.value) ?  value.includes(op.id) : op.selected  ) { ... }

isArray check is for the cases, where options is the only source of value. but after the first change (see below), we will have value and from then on, we can ignore the options

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +  public listOptions: SelectGroupOption[] = [];
you will not need this one (see below)

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.html
> +                (selectChange)="onListChange($event)">
you will also need to bind [value]="value" (see other comments for explanation)

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +  }
ListChange can take second argument - the selected IDs, so do:

`new ListChange(this.options, this.value)`

2020-11-17 14:59 UTC, galloween commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.ts
> +  }
so in this case, with the new approach, we dont need to touch the options, but instead:
- remove item.id from value
- call this.optionsToList(this.options, this.value)
- detectChanges

2020-11-18 08:17 UTC, SkyWallkeRed commented on projects/ui-framework/src/lib/lists/multi-list-and-list/multi-list-and-list.component.html
> +                (selectChange)="onListChange($event)">
b-basic-list dont support [value] as input

2020-11-18 12:26 UTC, galloween approved these changes

2020-11-18 14:01 UTC, merged

2020-11-18 15:14 UTC, oridanus commented
![party](https://user-images.githubusercontent.com/10963745/99548416-4e0f8900-29c1-11eb-888b-ac3ca7a86cf6.gif)