Daniel/delete confirmation dialog
hibobio/bob-style pull request #1830
Opened 2020-11-16 17:03 UTC by malkind

2020-11-17 14:20 UTC, galloween requested changes
I think it could be a little more organized, currently you have 2 places where you validate with 2 different methods.

if i was doing it, i would:
- validate on input blur (check inputEvents for type)
- disable/enable OK button and show/hide error message depending on validation 
- ok button just calls the action OR if the action is not a function or missing, returns whatever its supposed to return - Promise.resolve(true) probably

separately, i think everything should have fallbacks - i mean texts, so this should be expected to be usable without passing any config at all.

2020-11-17 14:20 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.html
> +      (inputEvents)="onInputEvent($event)">
it would be nice if there were fallbacks for everything - label, placeholder, hint

2020-11-17 14:20 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/confirmation-dialog.interface.ts
> +  errorMessage?: string;
if  label, placeholder, hint are optional - you need to provide default fallbacks in the component
maybe confirmationText should also have a fallback and be optional

2020-11-17 14:20 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +      }
why do you need to save it to const? 
you can just `return  this.config.buttonConfig.ok.action()`

2020-11-17 14:20 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +      }
maybe its also a good idea to check    if  `isFunction(this.config.buttonConfig.ok.action)`

2020-11-17 14:20 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +
i dont think you use these

2020-11-17 14:20 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +  }
you should have only 1 validation method 
`this.bInput.value. === this.config.confirmationData.confirmationText`

2020-11-17 14:20 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +  }
this will happen on every keystroke.
i think it should be validated either only on blur - if `input.event === InputEvent.OnBlur`
+ it would be a good idea to disable the ok button if there is an error
+ you should be using only 1 validation method - the one in isValid()

2020-11-18 13:25 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +      }
it won't work since it will just call itself over and over again. so this is why i'm saving the "original" CB function.
on the other hand, you suggested above to disable the ok button unless the text matches what we need, so if I do that, I  will not have to pass a different ok action to the dialog.

2020-11-18 13:35 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +  }
I don't like the onBlur option because this way you cannot type the work and immediately press "ok". you will have to click outside somewhere, let it update, and then click "ok".

plus I don't see any problem with the function being called on every keystroke, since there is no IO here.

2020-11-18 13:53 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/confirmation-dialog.interface.ts
> +  errorMessage?: string;
not sure how it's going to work
if they pass only confirmationText and pass neither label nor hintMessage, how should the user know what to type?

maybe I should make the label mandatory and all the rest optional.
@galloween

2020-11-18 17:27 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/confirmation-dialog.interface.ts
> +  errorMessage?: string;
but it's supposed to be the same dialog most of the time, isnt it?
you need confirm you want to delete something.

correct me if I miss something.

it would be great to be able to use it without any config at all!

as for fallbacks, I think its easiest to put them in the template:
`[label]="config.confirmationData.label || ('some.default.translation' | translate)"` etc

2020-11-18 17:30 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/confirmation-dialog.interface.ts
> +  errorMessage?: string;
or anywhere some prop from config is used:

`return this.bInput.value === (this.config.confirmationData.confirmationText || this.translate.instant('some.default.translation'))`

2020-11-18 18:15 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +  }
the only problem is it will be screaming the error in user's face before he finished typing...
so you need to at least debounce it..

by the way, it can be cool to make it all reactive:

```
valid$: Observable<boolean>;

this.valid$ = merge(
      this.bInput.changed.pipe(
        filter((event) => event.event !== InputEventType.onBlur),
        debounceTime(500)
      ),
      this.bInput.changed.pipe(
        filter((event) => event.event === InputEventType.onBlur)
      )
    ).pipe(
      map(
        (event) =>
          event.value ===
          (this.config.confirmationData?.confirmationText ||
            this.translate.instant('some.default.translation'))
      ),
      distinctUntilChanged()
    );
```
```
buttonConfig$: Observable<ConfirmationDialogButtons>

this.buttonConfig$ = valid$.pipe(
      startWith(false),
      map((valid) => {
        return {
          ...config.buttonConfig,
         cancel: {
           label: this.translate.instant('common.cancel'),
           ...this.config.buttonConfig.cancel,
          }
          ok: {
            label: this.translate.instant('common.ok'),
            ...this.config.buttonConfig.ok,
            disabled: !valid,
          },
        };
      })
    );
```
```
<b-dialog [dialogTitle]="config.title || ('default.title' | translate)"
          [dialogButtons]="buttonConfig$ | async">
  <div b-dialog-content>
    <p class="message" [innerHTML]="config.message || ('default.message' | translate)"></p>

    <b-input 
      [label]="config.confirmationData.label || ('default.label' | translate)"
      [placeholder]="config.confirmationData.placeholder || ('default.placeholder' | translate)"
      [hintMessage]="config.confirmationData.hintMessage || ('default.hint' | translate)"
      [errorMessage]="(valid$ | async) === false && (config.confirmationData.errorMessage || ('default.error' | translate))">
    </b-input>
  </div>
</b-dialog>
```

2020-11-18 18:19 UTC, galloween reviewed
see comments - maybe you want to make it reactive?

i got carried away a bit with the code for it, sorry, 
but the key takeaway things there are:
- you can subscribe to input's change event from the viewchild
- you can split it be event type and debounce the typing, but not the blur

2020-11-18 18:19 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +  @ViewChild('bInput') bInput: InputComponent;
Viewchild can also select by the component/directive/whatever, and then you dont need the #name:

`@ViewChild(InputComponent) bInput: InputComponent;`

2020-11-22 14:33 UTC, galloween reviewed
see comments

2020-11-22 14:33 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +          },
again, you need config?.buttonConfig?. etc

2020-11-22 14:33 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +    this.setDefaultValues();
you can also move these to constructor body (so that values exist before first change detection, and they will not need to re-render after OnInit)

2020-11-22 14:33 UTC, galloween commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +    this.sub = merge(
if you add static: true to the viewchild, the input will be available in ngOnInit

2020-11-22 16:34 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +
thanks!

2020-11-22 16:51 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +  private validitySubject: Subject<boolean> = new Subject();
removed the subject

2020-11-22 16:51 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/confirmation-dialog.service.ts
> +  openDeleteConfirmationDialog(config: ConfirmationDialogConfig): MatDialogRef<any> {
done

2020-11-22 16:52 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.html
> +</b-dialog>
done

2020-11-22 16:52 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +    this.sub.unsubscribe();
removed the subject. no more subscribe in the code.

2020-11-22 16:54 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +    });
why the "??"
config?property || default.value works.

2020-11-22 17:07 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +          (this.config.confirmationData?.confirmationText ||
nice!

2020-11-22 17:07 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +    this.setDefaultValues();
ok

2020-11-22 17:07 UTC, malkind commented on projects/ui-framework/src/lib/popups/confirmation-dialog/delete-confirmation-dialog/delete-confirmation-dialog.component.ts
> +    this.sub = merge(
thanks!!

2020-11-22 17:26 UTC, galloween approved these changes

2020-11-23 07:43 UTC, merged