insights component
hibobio/bob-style pull request #2065
Opened 2021-04-26 09:46 UTC by SkyWallkeRed

<img width="496" alt="Screen Shot 2021-04-26 at 12 45 06" src="https://user-images.githubusercontent.com/34270279/116063228-6a5cd380-a68d-11eb-8ab6-13ef33a18826.png">
<img width="505" alt="Screen Shot 2021-04-26 at 12 44 59" src="https://user-images.githubusercontent.com/34270279/116063243-6cbf2d80-a68d-11eb-9bb6-0bf34c064798.png">
<img width="1178" alt="Screen Shot 2021-04-26 at 12 44 49" src="https://user-images.githubusercontent.com/34270279/116063247-6df05a80-a68d-11eb-9af1-2724b166bca6.png">
<img width="1179" alt="Screen Shot 2021-04-26 at 12 44 43" src="https://user-images.githubusercontent.com/34270279/116063250-6f218780-a68d-11eb-9108-c3cb8030dca0.png">

2021-04-26 09:47 UTC, SkyWallkeRed commented
@galloween  ill add the test after your initial review :)

2021-04-28 06:37 UTC, galloween requested changes
Cool. now lets see if we can make it leaner and drier

2021-04-28 06:37 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.scss
> +    }
you dont have to repeat this block for each type

2021-04-28 06:37 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.scss
> +}
use .inl-blk class instead

2021-04-28 06:37 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.ts
> +  }
move constructor to the very beginning of the class, delete empty method

2021-04-28 06:37 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.stories.ts
> +          content: 'The number of leavers between Q1 2020 and Q4 2020 was highest in Kendall Roys team (13.25 per quarter), which is 73% of all company leavers. The number of leavers between Q1 2020
try to use some simple tags like <strong> and <br> here to see that html works.
you can also use color-classes as elements: <span class="clr-grey-600"> will work the same as <clr-grey-600>

2021-04-28 06:37 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.html
> +    <b-heading *ngIf="containerState === containerStates.contracted" class="heading uppercase mrg-y-16 mrg-l-8"> {{ contractButtonConf.text }} </b-heading>
mmm in the design the expand button is also a button with icon

<img width="143" alt="CleanShot 2021-04-28 at 09 18 00@2x" src="https://user-images.githubusercontent.com/2077754/116356710-4d96dc00-a804-11eb-8da6-210e0f1b4641.png">

you could do something like 
```
<b-button size="small" [icon]="icon"> <span class="b-heading uppercase"> text </span></b-button>
```

to move the icon on the other side you can use this mixin:
```
 .some-button ::ng-deep button[class*='b-icon'] {
    @include button-icon-right;
 }
```
for bg color you will also have to use css

2021-04-28 06:46 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.scss
> +
use this approach to make paddings easily correctable from outside via classes:
```
&:not([class*='pad-']) {
  padding: 10px;
}
```

2021-04-28 06:51 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.html
> +    <div class="pad-b-32" *ngFor="let insight of data">
- add trackBy
- use margin instead of padding
- remove margin from last item
```
<div *ngFor="let insight of data; let last = last; trackBy: ('$index' | trackByProp)" 
              [class.mrg-b-32]="!last" >
```

2021-04-28 07:01 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.scss
> +  border-radius: $border-radius;
maybe you want this only on the collapsed state.

in figma the expanded state sometimes doesnt have radius and sometimes its only on one side. 
so maybe its better to let it be provided from outside

2021-05-02 07:47 UTC, SkyWallkeRed commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.html
> +    <b-button class="btn-minimize mrg-b-8 mrg-y-8"
no, it sets the btn in the container

2021-05-02 20:23 UTC, galloween reviewed
maybe you could clean it up a little bit more, as much as you can :)
then merge!

2021-05-02 20:23 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.scss
> +  flex-grow: 1;
not sure about this one.
it may make the container stretch vertically (and/or horizontally), even when its collapsed.
i'd say, remove.

2021-05-02 20:23 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.ts
> +  };
expandButton ? (if we are using 'expand' word in other places)

also, you sure it needs to be an input?

if you think someone may need to customize the button, then maybe it can be on the config,
otherwise maybe add just the `config.expandButtonText`, and the rest  can be a readonly prop/const.

2021-05-02 20:23 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.ts
> +  }
isnt this cool? :)

2021-05-02 20:23 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.ts
> +  public onContractClick(): void {
expandClick ?

2021-05-02 20:23 UTC, galloween commented on projects/ui-framework/src/lib/layout/insights-panel/insight-panel.interfaces.ts
> +  isBorderRadius?: boolean,
![image](https://user-images.githubusercontent.com/2077754/116826536-1a09d800-ab9d-11eb-846d-c2a5e9b7a50c.png)

2021-05-03 08:54 UTC, SkyWallkeRed commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.scss
> +  }
to not pad the btn on collapsed just the content on expand.

2021-05-03 09:01 UTC, SkyWallkeRed commented on projects/ui-framework/src/lib/layout/insights-panel/insights-panel.component.ts
> +  }
very!

2021-05-05 09:42 UTC, merged